name: Update fzf
on:
  workflow_dispatch:
  schedule:
    # at 21:00 on every Saturday (UTC) = at 6:00 on every Sunday (JST)
    - cron: "0 21 * * SAT"
jobs:
  update-fzf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update fzf
        run: |
          set -x
          CURRENT_VERSION=$(cat fzf-version)
          LATEST_VERSION=$(
            curl -s "https://api.github.com/repos/junegunn/fzf/releases/latest" | \
            jq --exit-status -r .tag_name
          )
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "$LATEST_VERSION" >fzf-version
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            BRANCH="update-fzf-${LATEST_VERSION}"
            if git checkout -b "$BRANCH"; then
              git add fzf-version
              git commit -m "Update fzf to ${LATEST_VERSION}"
              git push origin "$BRANCH"
              gh pr create --base master --head "$BRANCH" --title "Update fzf to ${LATEST_VERSION}" --body ""
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
